name: Merge to Branch 1

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Check if the merge label is present
      run: echo "${{ toJSON(github.event.pull_request.labels.*.name) }}"
        #      if: false == contains(github.event.pull_request.labels.*.name, 'Merge to Branch 1')
        #      run: exit 1

  merge:
    needs: check
    
    if: needs.check.outputs.status == 'success'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Create the holding pen branch if it doesn't exist
      run: |
        git fetch --all

        BRANCH_NAME="branch_1_holding_pen"

        if git show-ref --quiet refs/heads/$BRANCH_NAME; then
          echo "Branch '$BRANCH_NAME' already exists."
        else
          echo "Branch '$BRANCH_NAME' does not exist. Creating new branch."
          git checkout -b $BRANCH_NAME
          git push origin $BRANCH_NAME
        fi

        #    - name: Merge this commit to the holding pen
        #      run: |

