name: Merge to Branch 1

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  merge_upstream:

    if: |
      contains(github.event.pull_request.labels.*.name, 'Merge to Branch 1') &&
      github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4.1.7
      with:
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Get the last commit SHA from the PR's branch
      run: |
       git checkout ${{ github.event.pull_request.head.ref }}
       OUTPUT=$(git rev-parse HEAD)
       echo "LAST_SHA=$OUTPUT" >> $GITHUB_ENV

    - name: Check out the holding pen branch
      run: |
        git fetch --all

        BRANCH_NAME="branch_1_holding_pen"

        if git show-ref --quiet refs/remotes/origin/$BRANCH_NAME; then
          git checkout $BRANCH_NAME
          echo "Branch '$BRANCH_NAME' already exists."
        else
          echo "Branch '$BRANCH_NAME' does not exist. Creating new branch."
          git checkout -b $BRANCH_NAME
          git push origin $BRANCH_NAME
        fi

    - name: Cherry-pick this commit to the holding pen
      run: |
        git cherry-pick --abort || true
        git cherry-pick $LAST_SHA || git cherry-pick --abort
        git push origin $BRANCH_NAME
