name: Merge to Branch 1

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  merge_upstream:

    if: |
      contains(github.event.pull_request.labels.*.name, 'Merge to Branch 1') &&
      github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Set up Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Create the holding pen branch if it doesn't exist
      run: |
        git fetch --all

        BRANCH_NAME="branch_1_holding_pen"

        if git show-ref --quiet refs/remotes/origin/$BRANCH_NAME; then
          echo "Branch '$BRANCH_NAME' already exists."
        else
          echo "Branch '$BRANCH_NAME' does not exist. Creating new branch."
          git checkout -b $BRANCH_NAME
          git push origin $BRANCH_NAME
        fi

    - name: Get the last commit SHA
      id: last_commit
      run: echo "::set-output name=sha::$(git rev-parse HEAD)"

    - name: Check out the holding pen branch
      run: git checkout $BRANCH_NAME

    - name: Cherry-pick this commit to the holding pen
      run: |
        git cherry-pick ${{ steps.last_commit.outputs.sha }}
        git push origin $BRANCH_NAME
